<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Accommodation;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $host_user_id int(10,0) unsigned NOT NULL
 * @property mixed $city varchar(255) NOT NULL
 * @property mixed $address varchar(255) NOT NULL
 * @property mixed $price int(10,0) unsigned NOT NULL
 * @property mixed $type enum(12) NOT NULL
 * @property mixed $has_washer tinyint(3,0) unsigned NOT NULL
 * @property mixed $has_wifi tinyint(3,0) unsigned NOT NULL
 * @property mixed $has_tv tinyint(3,0) unsigned NOT NULL
 * @property mixed $date_created timestamp NOT NULL
 */
class AccommodationRow extends Row
{
    protected $cols = [
        'id' => null,
        'host_user_id' => null,
        'city' => null,
        'address' => null,
        'price' => null,
        'type' => null,
        'has_washer' => null,
        'has_wifi' => null,
        'has_tv' => null,
        'date_created' => '0000-00-00 00:00:00',
    ];
}
