<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Accommodation;

use Atlas\Table\Table;

/**
 * @method AccommodationRow|null fetchRow($primaryVal)
 * @method AccommodationRow[] fetchRows(array $primaryVals)
 * @method AccommodationTableSelect select(array $whereEquals = [])
 * @method AccommodationRow newRow(array $cols = [])
 * @method AccommodationRow newSelectedRow(array $cols)
 */
class AccommodationTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'accommodation';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'host_user_id' => array (
  'name' => 'host_user_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'city' => array (
  'name' => 'city',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'address' => array (
  'name' => 'address',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'price' => array (
  'name' => 'price',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'type' => array (
  'name' => 'type',
  'type' => 'enum',
  'size' => 12,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => 
  array (
    0 => '\'entire_home\'',
    1 => '\'private_room\'',
    2 => '\'shared_room\'',
  ),
),
        'has_washer' => array (
  'name' => 'has_washer',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'has_wifi' => array (
  'name' => 'has_wifi',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'has_tv' => array (
  'name' => 'has_tv',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'date_created' => array (
  'name' => 'date_created',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => '0000-00-00 00:00:00',
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'host_user_id',
        'city',
        'address',
        'price',
        'type',
        'has_washer',
        'has_wifi',
        'has_tv',
        'date_created',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'host_user_id' => null,
        'city' => null,
        'address' => null,
        'price' => null,
        'type' => null,
        'has_washer' => null,
        'has_wifi' => null,
        'has_tv' => null,
        'date_created' => '0000-00-00 00:00:00',
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
