<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Reservation;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $accommodation_id int(10,0) unsigned NOT NULL
 * @property mixed $guest_user_id int(10,0) unsigned NOT NULL
 * @property mixed $date_from date NOT NULL
 * @property mixed $date_to date NOT NULL
 * @property mixed $date_created timestamp NOT NULL
 */
class ReservationRow extends Row
{
    protected $cols = [
        'id' => null,
        'accommodation_id' => null,
        'guest_user_id' => null,
        'date_from' => null,
        'date_to' => null,
        'date_created' => '0000-00-00 00:00:00',
    ];
}
