<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Reservation;

use Atlas\Table\Table;

/**
 * @method ReservationRow|null fetchRow($primaryVal)
 * @method ReservationRow[] fetchRows(array $primaryVals)
 * @method ReservationTableSelect select(array $whereEquals = [])
 * @method ReservationRow newRow(array $cols = [])
 * @method ReservationRow newSelectedRow(array $cols)
 */
class ReservationTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'reservation';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'accommodation_id' => array (
  'name' => 'accommodation_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'guest_user_id' => array (
  'name' => 'guest_user_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'date_from' => array (
  'name' => 'date_from',
  'type' => 'date',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'date_to' => array (
  'name' => 'date_to',
  'type' => 'date',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'date_created' => array (
  'name' => 'date_created',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => '0000-00-00 00:00:00',
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'accommodation_id',
        'guest_user_id',
        'date_from',
        'date_to',
        'date_created',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'accommodation_id' => null,
        'guest_user_id' => null,
        'date_from' => null,
        'date_to' => null,
        'date_created' => '0000-00-00 00:00:00',
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
