<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\User;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(225) NOT NULL
 * @property mixed $date_created timestamp NOT NULL
 */
class UserRow extends Row
{
    protected $cols = [
        'id' => null,
        'name' => null,
        'date_created' => '0000-00-00 00:00:00',
    ];
}
