<?php

declare(strict_types=1);

namespace App;

final class Samples
{
    const CITIES = [
        'Abbotsford',
        'Burnaby',
        'Chilliwack',
        'Coquitlam',
        'Kamloops',
        'Kelowna',
        'Maple Ridge',
        'Nanaimo',
        'New Westminster',
        'North Vancouver',
        'Port Coquitlam',
        'Prince George',
        'Richmond',
        'Surrey',
        'Vancouver',
        'Victoria',
    ];

    const NAMES = [
        'Aaron',
        'Adam',
        'Alan',
        'Albert',
        'Andrew',
        'Anthony',
        'Antonio',
        'Arthur',
        'Benjamin',
        'Billy',
        'Bobby',
        'Brandon',
        'Brian',
        'Bruce',
        'Carl',
        'Carlos',
        'Charles',
        'Chris',
        'Christopher',
        'Clarence',
        'Craig',
        'Daniel',
        'David',
        'Dennis',
        'Donald',
        'Douglas',
        'Earl',
        'Edward',
        'Eric',
        'Ernest',
        'Eugene',
        'Frank',
        'Fred',
        'Gary',
        'George',
        'Gerald',
        'Gregory',
        'Harold',
        'Harry',
        'Henry',
        'Howard',
        'Jack',
        'James',
        'Jason',
        'Jeffrey',
        'Jeremy',
        'Jerry',
        'Jesse',
        'Jimmy',
        'Joe',
        'John',
        'Johnny',
        'Jonathan',
        'Jose',
        'Joseph',
        'Joshua',
        'Juan',
        'Justin',
        'Keith',
        'Kenneth',
        'Kevin',
        'Larry',
        'Lawrence',
        'Louis',
        'Mark',
        'Martin',
        'Matthew',
        'Michael',
        'Nicholas',
        'Patrick',
        'Paul',
        'Peter',
        'Philip',
        'Phillip',
        'Ralph',
        'Randy',
        'Raymond',
        'Richard',
        'Robert',
        'Roger',
        'Ronald',
        'Roy',
        'Russell',
        'Ryan',
        'Samuel',
        'Scott',
        'Sean',
        'Shawn',
        'Stephen',
        'Steve',
        'Steven',
        'Terry',
        'Thomas',
        'Timothy',
        'Todd',
        'Victor',
        'Walter',
        'Wayne',
        'William',
        'Willie',

        'Alice',
        'Amanda',
        'Amy',
        'Andrea',
        'Angela',
        'Ann',
        'Anna',
        'Anne',
        'Annie',
        'Ashley',
        'Barbara',
        'Betty',
        'Beverly',
        'Bonnie',
        'Brenda',
        'Carol',
        'Carolyn',
        'Catherine',
        'Cheryl',
        'Christina',
        'Christine',
        'Cynthia',
        'Deborah',
        'Debra',
        'Denise',
        'Diana',
        'Diane',
        'Donna',
        'Doris',
        'Dorothy',
        'Elizabeth',
        'Emily',
        'Evelyn',
        'Frances',
        'Gloria',
        'Heather',
        'Helen',
        'Irene',
        'Jacqueline',
        'Jane',
        'Janet',
        'Janice',
        'Jean',
        'Jennifer',
        'Jessica',
        'Joan',
        'Joyce',
        'Judith',
        'Judy',
        'Julia',
        'Julie',
        'Karen',
        'Katherine',
        'Kathleen',
        'Kathryn',
        'Kathy',
        'Kelly',
        'Kimberly',
        'Laura',
        'Lillian',
        'Linda',
        'Lisa',
        'Lois',
        'Lori',
        'Louise',
        'Margaret',
        'Maria',
        'Marie',
        'Marilyn',
        'Martha',
        'Mary',
        'Melissa',
        'Michelle',
        'Mildred',
        'Nancy',
        'Nicole',
        'Norma',
        'Pamela',
        'Patricia',
        'Paula',
        'Phyllis',
        'Rachel',
        'Rebecca',
        'Robin',
        'Rose',
        'Ruby',
        'Ruth',
        'Sandra',
        'Sara',
        'Sarah',
        'Sharon',
        'Shirley',
        'Stephanie',
        'Susan',
        'Tammy',
        'Teresa',
        'Theresa',
        'Tina',
        'Virginia',
        'Wanda',
    ];

    const STREETS = [
        '10th Ave West',
        '12th Ave',
        '16th Ave',
        '1st Ave',
        '33rd Ave',
        '41st Ave',
        '49th Ave',
        '4th Ave',
        '57th Ave',
        '70th Ave',
        'Alma St',
        'Arbutus St',
        'Boundary Road',
        'Broadway',
        'Burrard St',
        'Cambie St',
        'Clark Drive North',
        'Commercial Drive',
        'Cordova St',
        'Davie St',
        'Denman St',
        'Dunbar St',
        'Dunsmuir St',
        'Fraser St',
        'Georgia St',
        'Grandview Highway',
        'Granville St',
        'Hastings St West',
        'Howe St',
        'Joyce St',
        'King Edward Ave',
        'Kingsway',
        'Knight St',
        'Macdonald St',
        'Main St',
        'Marine Drive',
        'McGill St West',
        'Nanaimo St',
        'Nelson St',
        'Oak St',
        'Pacific Boulevard',
        'Prior St/Venables St',
        'Renfrew St',
        'Robson St',
        'Rupert St/Kerr St',
        'Seymour St',
        'Smithe St',
        'Terminal Ave',
        'Thurlow St',
    ];

    private function __construct()
    {
    }
}
